config:
  #插件兼容
  integration:
    Residence: false
    WorldGuard: false
    Kingdoms: false
    GriefDefender: false
    PlotSquared: false
    Towny: false
    Lands: false
    AureliumSkills: false
    mcMMO: false
    MMOCore: false

  #生长时间点(tick)
  #1000代表上午7点，农作物陆续开始生长
  #洒水器将会在农作物全部完成生长后开始工作
  grow-time:
    - 1000

  #生长点后农作物成长所需的时间（秒）
  #农作物将在60秒内随机完成生长以避免在短时间内大量方块替换造成卡顿
  #但也不建议设置过长时间，否则内存无法及时释放，区块会被持续加载
  #配合上方的默认时间点，意思为每天上午7点后，农作物将在60秒内完成生长过程
  time-to-grow: 60
  #农作物全部完成生长后洒水器工作所需的时间
  time-to-work: 30

  #产物品质
  quality:
    #若不启用则植物成熟阶段会掉落IA配置里的loot
    #如果关闭产物品质需要在IA物品配置内自行添加最后一阶段掉落物
    enable: true
    #默认品质权重比
    default-ratio: 17/2/1

  #异步时间检测，此设置需要重启生效
  #启用异步时间检测会带来更好的性能但是可能会因为服务器的跳tick原因错过一些生长时间点
  async-time-check: false

  #使用一次水桶可以补充几个洒水器水槽
  sprinkler-refill: 2
  #水壶右键一次水方块能补充多少水量
  water-can-refill: 1
  #是否可以用水壶为洒水器加水
  water-can-add-water-to-sprinkler: true
  #使用水的时候是否产生粒子效果
  water-particles: true

  #生长生效的世界
  whitelist-worlds:
    - world

  #每个区块最大农作物数量和洒水器数量
  #是否启用限制
  limit:
    enable: true
    crop: 64
    sprinkler: 8

  #记录生长判断和洒水所需的时间(测试性能用)
  log-time-consume: false

  #Mode 1:
  #  加载中区块的农作物生长
  #Mode 2:
  #  在线玩家的农作物生长
  #Mode 3:
  #  Mode 1 + Mode 2
  #Mode 4:
  #  所有农作物生长
  #  可能会造成卡顿！不建议使用此模式
  grow-mode: 3

  #是否所有加载中的世界都要进行生长判断
  #本选项适用于使用玩家独立世界的服务器
  #因为有大量世界所以无法通过添加白名单世界的方式生长
  #在此选项开启的状态下，白名单世界只能填写一个
  #作为所有世界农作物生长的时间、季节判断依据
  all-world-grow: false

  #玩家是否能右键收获
  right-click-harvest: true

  #玩家是否需要空手右键收获
  harvest-with-empty-hand: true

  #是否阻止玩家在错误的季节种植
  prevent-plant-if-wrong-season: true
  #是否告知玩家这是错误的季节
  should-notify-if-wrong-season: true

  #骨粉设置
  bone-meal:
    enable: true
    chance: 0.5
    success-particle: VILLAGER_HAPPY