sprinkler_1:
  # This decides the work range
  # (1+1x2)²=9
  range: 1
  storage: 5
  3D-item: customcrops:sprinkler_1
  2D-item: customcrops:sprinkler_1_item
  # Item_Frame / Tripwire / Item_Display (1.19.4+)
  type: Item_Frame
  place-sound: minecraft:block.bone_block.place
  hologram:
    enable: true
    # ARMOR_STAND / TEXT_DISPLAY (1.19.4+)
    type: ARMOR_STAND
    y-offset: 0.8
    duration: 1
    # Available variables:
    # {water_bar} water bar image
    # {current} current water
    # {storage} max storage
    content: '<font:customcrops:default>{water_bar}</font>'
    water-bar:
      left: '뀂'
      full: '뀁뀃'
      empty: '뀁뀄'
      right: '뀁뀅'
  # Water splash animation when sprinkler works
  sprinkler-animation:
    enable: true
    y-offset: 0.4
    item: customcrops:water_animation
    # ARMOR_STAND / ITEM_DISPLAY (1.19.4+)
    type: ARMOR_STAND
  pot-whitelist:
    - default
  fill-method:
    method_1:
      item: WATER_BUCKET
      return: BUCKET
      amount: 3
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient
    method_2:
      item: WATER
      return: GLASS_BOTTLE
      amount: 1
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient

sprinkler_2:
  # (1+2x2)²=25
  range: 2
  storage: 5
  3D-item: customcrops:sprinkler_2
  2D-item: customcrops:sprinkler_2_item
  type: Item_Frame
  place-sound: minecraft:block.bone_block.place
  hologram:
    enable: true
    type: ARMOR_STAND
    y-offset: 0.8
    duration: 1
    content: '<font:customcrops:default>{water_bar}</font>'
    water-bar:
      left: '뀂'
      full: '뀁뀃'
      empty: '뀁뀄'
      right: '뀁뀅'
  sprinkler-animation:
    enable: true
    y-offset: 0.4
    item: customcrops:water_animation
    type: ARMOR_STAND
  pot-whitelist:
    - default
  fill-method:
    method_1:
      item: WATER_BUCKET
      return: BUCKET
      amount: 3
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient
    method_2:
      item: WATER
      return: GLASS_BOTTLE
      amount: 1
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient

sprinkler_3:
  range: 2
  storage: 7
  3D-item: customcrops:sprinkler_3
  2D-item: customcrops:sprinkler_3_item
  type: Item_Frame
  place-sound: minecraft:block.bone_block.place
  hologram:
    enable: true
    type: ARMOR_STAND
    y-offset: 0.8
    duration: 1
    content: '<font:customcrops:default>{water_bar}</font>'
    water-bar:
      left: '뀂'
      full: '뀁뀃'
      empty: '뀁뀄'
      right: '뀁뀅'
  sprinkler-animation:
    enable: true
    y-offset: 0.4
    item: customcrops:water_animation
    type: ARMOR_STAND
  pot-whitelist:
    - default
  fill-method:
    method_1:
      item: WATER_BUCKET
      return: BUCKET
      amount: 3
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient
    method_2:
      item: WATER
      return: GLASS_BOTTLE
      amount: 1
      particle: WATER_SPLASH
      sound: minecraft:block.water.ambient