# Don't change
config-version: '25'
# BStats
metrics: true
# Language: english / spanish / chinese / turkish
lang: english
# Set up mode
set-up-mode: true
# AntiGrief
integrations:
  Residence: false
  WorldGuard: false
  Kingdoms: false
  GriefDefender: false
  PlotSquared: false
  Towny: false
  Lands: false
  GriefPrevention: false
  CrashClaim: false
  BentoBox: false
  IridiumSkyBlock: false
  SuperiorSkyBlock: false

worlds:
  # This is designed for servers that using a separate folder for worlds
  # The default folder is your server's root folder
  # 如果你的服务器使用独立文件夹存储世界，请在此填入根目录下的文件地址
  folder: ''
  # Mode: whitelist/blacklist
  # Requires a restart when changing mode or editing world list for the safety of data
  # 模式：白名单/黑名单
  # 为了避免重载时候造成服务器卡顿，修改本栏需要重启服务器
  mode: whitelist
  list:
    - world

schedule-system:
  enable: true
  # The average interval for a crop to gain one point (measured in seconds)
  # 平均每个农作物获得一生长点的时间间隔（秒）
  point-gain-interval: 10
  # Thread pool settings
  # 线程池设置
  thread-pool-settings:
    # 核心线程池大小
    corePoolSize: 2
    # 最大线程池大小
    maximumPoolSize: 4
    # seconds (秒)
    keepAliveTime: 10

optimization:
  # Recommend enabling this to prevent large quantities of crops/item frames from lagging the server
  # When you are using both item_frame mode and ItemsAdder, you should set "max-furniture-vehicles-per-chunk" in ItemsAdder's config.yml to a higher value
  # 推荐启用区块限制来防止玩家种植大量农作物
  # 如果你使用ItemsAdder的展示框模式，你需要在ItemsAdder的配置文件中设置"max-furniture-vehicles-per-chunk"到较高值，否则农作物种植后会消失
  limitation:
    enable: true
    # max amount per chunk
    # 每个区块的限制数量
    valid-crop-amount: 64

mechanics:
  # 17/2/1 = 85%/10%/5%
  # 2/2/1 = 40%/40%/20%
  default-quality-ratio: 17/2/1

  # Season mechanic
  # 季节机制
  season:
    enable: true
    # If you want all the worlds to share the same season
    # 是否全世界同步季节
    sync-season:
      enable: false
      reference: world
    # 自动季节交替
    auto-season-change:
      enable: true
      # duration of each season (Minecraft days)
      # 每个季节的时长
      duration: 28
    greenhouse:
      enable: true
      block: customcrops:greenhouse_glass
      # effective range (Y axis)
      # Y轴有效范围
      range: 5

other-settings:
  # This option requires a skill-plugin hook
  # Which would increase the amount of crops player get
  # 这需要一个技能插件才能生效，可以根据玩家种植技能等级提供增益
  skill-bonus:
    enable: false
    formula: '{base} + {level} * 0.01'
  # MMOCore profession name
  # MMOCore职业名
  MMOCore-profession-name: 'farmer'