# Don't change
config-version: '27'
# BStats
metrics: true
# Language: english / spanish / chinese / turkish
lang: english
# debug
debug: false

worlds:
  # This is designed for servers that using a separate folder for worlds
  # 如果你的服务器使用独立文件夹存储世界，请在此填入绝对地址
  absolute-world-folder-path: ''
  # Mode: whitelist/blacklist
  # Requires a restart when changing mode or editing world list for the safety of data
  # 模式：白名单/黑名单
  # 为了避免重载时候造成服务器卡顿，修改本栏需要重启服务器
  mode: whitelist
  list:
    - world

schedule-system:
  # Water amount and fertilizer use would be reduced at 6am
  # Sprinklers would work at 7am
  # if disabled, you can do that manually with command /customcrops force [consume/sprinklerwork]
  # 水分和肥料将在每天6点减少，洒水器将在7点工作
  # 如果禁用，你可以使用指令/customcrops force [consume/sprinklerwork]手动操作
  default-schedule: true
  # The average interval for a crop to gain one point (measured in seconds)
  # 平均每个农作物获得一生长点的时间间隔（秒）
  point-gain-interval: 1200
  # Save cache to file interval (seconds)
  # set "-1" to disable
  # 保存缓存的时间间隔 (秒)
  cache-save-interval: 7500
  # Thread pool settings
  # 线程池设置
  thread-pool-settings:
    # 核心线程池大小
    corePoolSize: 1
    # 最大线程池大小
    maximumPoolSize: 4
    # seconds (秒)
    keepAliveTime: 10

optimization:
  # Recommend enabling this to prevent large quantities of crops/item frames from lagging the server
  # When you are using both item_frame mode and ItemsAdder, you should set "max-furniture-vehicles-per-chunk" in ItemsAdder's config.yml to a higher value
  # 推荐启用区块限制来防止玩家种植大量农作物
  # 如果你使用ItemsAdder的展示框模式，你需要在ItemsAdder的配置文件中设置"max-furniture-vehicles-per-chunk"到较高值，否则农作物种植后会消失
  limitation:
    # max crop amount per chunk
    # 每个区块的限制数量
    growing-crop-amount:
      enable: true
      default: 48
      # settings for a specified world
      # 指定世界的设置
      worlds:
        - world:64

mechanics:
  # 17/2/1 = 85%/10%/5%
  # 2/2/1 = 40%/40%/20%
  default-quality-ratio: 17/2/1

  # Season mechanic
  # 季节机制
  season:
    enable: true
    # If you want all the worlds to share the same season
    # 是否全世界同步季节
    sync-season:
      enable: false
      reference: world
    # 自动季节交替
    auto-season-change:
      enable: true
      # duration of each season (Minecraft days)
      # 每个季节的时长
      duration: 28
    greenhouse:
      enable: true
      block: customcrops:greenhouse_glass
      # effective range (Y axis)
      # Y轴有效范围
      range: 5
  # scarecrow item id
  # 稻草人物品id
  scarecrow: customcrops:scarecrow

other-settings:
  # This option requires a skill-plugin hook
  # Which would increase the amount of crops player get
  # 这需要一个技能插件才能生效，可以根据玩家种植技能等级提供增益
  skill-bonus:
    enable: false
    formula: '{base} + {level} * 0.01'
  # MMOCore profession name
  # MMOCore职业名
  MMOCore-profession-name: 'farmer'