#Don't change
config-version: '9'



# lang: english / spanish / chinese
lang: chinese



integration:
  # AntiGrief
  Residence: false
  WorldGuard: false
  Kingdoms: false
  GriefDefender: false
  PlotSquared: false
  Towny: false
  Lands: false
  GriefPrevention: false
  CrashClaim: false
  BentoBox: false
  # Skill Xp
  AureliumSkills: false
  mcMMO: false
  MMOCore: false
  EcoSkills: false
  JobsReborn: false
  # Season
  RealisticSeasons: false



worlds:
  # Mode: whitelist/blacklist
  mode: whitelist
  list:
    - world



crops:
  # Mode: tripwire/item_frame
  mode: tripwire



optimization:
  # Recommend enabling this to prevent large quantities of crops/itemframes lagging the server
  limitation:
    enable: true
    tripwire-amount: 64
    itemframe-amount: 64

  # Async time check
  async-time-check: false



mechanics:
  # Can player harvest crops with right click?
  # if set "false" crops can't be harvested repeatedly
  right-click-harvest:
    enable: true
    require-empty-hand: true
  # Should player be prevented from planting if wrong season
  prevent-plant-if-wrong-season: true
  # Should player be notified of the wrong season?
  should-notify-if-wrong-season: true
  #
  fill:
    watering-can-to-sprinkler: 1
    water-bucket-to-sprinkler: 3
    waterblock-to-watering-can: 1

  # Will bone meal accelerate the growth of crop
  bone-meal:
    enable: true
    chance: 0.5
    success-particle: VILLAGER_HAPPY
  # Season mechanic
  # Crops would go to death stage if growing in wrong seasons
  # Season would not affect ripe crops(for better performance and friendly player's experience)
  season:
    enable: true
    auto-season-change:
      enable: true
      #duration of each season
      duration: 28
    greenhouse:
      enable: true
      #effective range
      range: 5
  crow:
    enable: true
    chance: 0.001
  default-quality-ratio: 17/2/1



sounds:
  water-pot:
    enable: true
    sound: minecraft:block.water.ambient
    type: player
  add-water-to-can:
    enable: true
    sound: minecraft:item.bucket.fill
    type: player
  add-water-to-sprinkler:
    enable: true
    sound: minecraft:item.bucket.fill
    type: player
  place-sprinkler:
    enable: true
    sound: minecraft:block.bone_block.place
    type: player
  plant-seed:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  use-fertilizer:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  harvest-crops:
    enable: true
    sound: minecraft:block.crop.break
    type: player
  bonemeal:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  surveyor:
    enable: true
    sound: minecraft:block.note_block.pling
    type: player


#Hologram information
hologram:
  #Pot infomation
  fertilizer-info:
    enable: true
    y-offset: 0.8
    duration: 1
    text: '<font:customcrops:default>{fertilizer} </font><white>{times}<gray>/<white>{max_times}'
  #Sprinkler infomation
  sprinkler-info:
    enable: true
    y-offset: 0.8
    duration: 1
    #available variables {water} {max_water}
    left: '<font:customcrops:default>뀂'
    full: '뀁뀃'
    empty: '뀁뀄'
    right: '뀁뀅</font>'



actionbar:
  #Should actionbar be sent when using watering-can
  enable: true
  #available variables  {water} {max_water}
  left: '<font:customcrops:default>뀂'
  full: '뀁뀃'
  empty: '뀁뀄'
  right: '뀁뀅</font>'