enable-season: true
# Current season
# Use command "/customcrops setseason" to change season
# You can experience season feature by using "CMI schedule" or other Season plugin
current-season: spring

config:
  # The pot that crops can be planted in
  # format: namespace:item_id
  pot: customcrops:pot
  # Crops can only grow on watered pot
  watered-pot: customcrops:watered_pot

  # Watering Can
  # 1x1 range
  watering-can-1: customcrops:watering_can_1
  # 1x3 range
  watering-can-2: customcrops:watering_can_2
  # 1x5 range
  watering-can-3: customcrops:watering_can_3

  # enable greenhouse feature
  # crops can be planted under greenhouse glass
  enable-greenhouse: true
  # effective range
  greenhouse-range: 7
  greenhouse-glass: customcrops:greenhouse_glass

  # sprinkler furniture in ItemsAdder
  # 3x3 range
  sprinkler-1: customcrops:sprinkler_1
  # sprinkler item in ItemsAdder
  sprinkler-1-item: customcrops:sprinkler_1_item

  # 5x5 range
  sprinkler-2: customcrops:sprinkler_2
  sprinkler-2-item: customcrops:sprinkler_2_item

  # dead crops
  dead-crop: customcrops:crop_stage_death
  # The chance that crops grow every morning
  grow-success-chance: 0.8

  # The chance that using bone meal to skip one stage
  bone-meal-chance: 0.5
  # Will using bone meal consume water
  bone-meal-consume-water: true
  # Particle Effects
  particle:
    # Use bone meal
    success: HEART
    failure: VILLAGER_ANGRY
  # The height where crops can grow
  height:
    min: 50
    max: 100
  # should we limit the max number of crops and spinklers in chunks?
  # Maybe too many crops would cause lagggggggg
  enable-limit: true
  max-crops: 32
  max-sprinklers: 4
  # whitelist worlds where crops would grow
  whitelist-worlds:
    - world
  # should we only alow crops in loaded chunks to grow?
  # This is good for server performance
  only-grow-in-loaded-chunks: true

messages:
  prefix: '<gradient:#ccfbff:#ef96c5>[CustomCrops] </gradient>'
  not-a-good-place: 'That place is too high/low. Just try another place!'
  reload: 'Reloaded'
  force-save: 'Successfully save cache data!'
  no-such-seed: 'This seed is not configured in config.yml'
  wrong-season: 'You can not plant this crop in this season'
  season-set: 'Successfully change season to {Season}'
  season-disabled: 'Season is not enabled in this server'
  clean-cache: 'Successfully clean removed crops and sprinkler'
  reach-limit-crop: 'Too many crops. The limit is {Max} per chunk!'
  reach-limit-sprinkler: 'Too many sprinklers. The limit is {Max} per chunk!'
  backup: 'Back up Successfully'
  spring: 'spring'
  summer: 'summer'
  autumn: 'autumn'
  winter: 'winter'
  can-full: 'The watering can is already full!'

# Crops
crops:
  tomato:
    # Please name the crops with "_seeds" and "_stage_X"
    # Otherwise they would not grow
    # You can refer to the example configuration :)
    season: spring,autumn
    #return: customcrops:tomato_stage_3