config:
  #插件兼容
  integration:
    Residence: false
    WorldGuard: false
    Kingdoms: false
    GriefDefender: false
    PlotSquared: false
    Towny: false
    Lands: false

  #生长时间点(tick)
  #洒水器将会在农作物全部完成生长后开始工作
  #1000代表上午7点，农作物陆续开始生长
  grow-time:
    - 1000

  #生长的时间（秒）
  #农作物将在90秒内随机完成生长以避免在短时间内大量方块替换造成卡顿
  #但也不建议设置过长时间，否则内存无法及时释放，区块会被持续加载
  #配合上方的默认时间点，意思为每天上午7点后，农作物将在90秒内完成生长过程
  time-to-grow: 90

  #产物品质
  quality:
    #若不启用则植物成熟阶段会掉落IA配置里的loot
    #如果关闭产物品质需要在IA物品配置内自行添加最后一阶段掉落物
    #如果你使用的领地插件不被兼容，请不要启用产物品质功能，
    #请立即更换领地插件或寻找作者写领地兼容
    enable: true
    #默认品质权重比
    default-ratio: 17/2/1

  #异步时间检测，此设置需要重启生效
  #启用异步时间检测会带来更好的性能但是可能会因为服务器的跳tick原因错过一些生长时间点
  async-time-check: false

  #使用一次水桶可以补充几个洒水器水槽
  sprinkler-refill: 2

  #生长生效的世界
  whitelist-worlds:
    - world

  #每个区块最大农作物数量和洒水器数量
  #是否启用限制
  limit:
    enable: true
    crop: 64
    sprinkler: 8

  #记录生长判断和洒水所需的时间(测试性能用)
  log-time-consume: false

  #是否只有加载中的区块农作物才会生长
  #如果你不使用季节、可重复收获、巨大化农作物特性
  #插件data只会记录正在生长中某个阶段的农作物数据
  #生长到最后一阶段农作物生长数据就会清除
  #那么可以尝试设置此值为false来让数据内全部农作物生长
  #如果你使用上述三个特性中的任意一个，请不要设置为false
  #否则农作物生长到最后一阶段不会从数据中清除，过大的数据量
  #可能会导致服务器严重卡顿
  only-grow-in-loaded-chunks: true