config:
  #english spanish chinese
  lang: english


  integration:
    #integration to prevent other players' grief
    Residence: false
    WorldGuard: false
    Kingdoms: false
    GriefDefender: false
    PlotSquared: false
    Towny: false
    Lands: false
    GriefPrevention: false
    #integration to add players' farming skill xp
    AureliumSkills: false
    mcMMO: false
    MMOCore: false

  #The time to start growing(ticks)
  #1000ticks is 7am in game. (0-23999)
  #Sprinklers will work after all crops finish growing
  grow-time:
    - 1000

  #Time in random a single crop need to grow（seconds）
  #This prevents a large amount of crops grow at the same time
  #Large amount of block replacement would cause lag.
  time-to-grow: 60
  #Similar to "time-to-grow", this prevent all sprinklers work at the same time
  time-to-work: 30

  quality:
    #If disabled, you need to configurate the loot in ItemsAdder config
    enable: true
    #Default ratio
    default-ratio: 17/2/1

  #Async Time Check (requires restart)
  #Crops might not grow when using async.
  #It is not really necessary to be Async
  async-time-check: false

  #Water Amount to refill when using water bucket
  sprinkler-refill: 2
  #Water Amount to refill with a sigle click to water block 
  water-can-refill: 1
  #Can watering-can add water to sprinklers?
  water-can-add-water-to-sprinkler: true
  #Should particles be displayed when using watering can?
  water-particles: true

  #Worlds where crops would grow
  whitelist-worlds:
    - world

  #Should we limit the max amount of crops and sprinkler in one chunk
  #Recommended to enable because ItemsAdder might throw StackOverFlow 
  #when there are too many custom blocks in one chunk
  limit:
    enable: true
    crop: 64
    sprinkler: 8

  #Test performance
  log-time-consume: false

  #Defaultly crops will only grow in loaded chunks. 
  #If you want a mechanic similar to OriginRealms just DISABLE SEASON, GIGANTIC(OverWeight) and REPEATED HARVESTING.
  #In this way crops data will be removed from file after it comes to its final stage.
  #In other words, plugin will only record the crops still on growing.
  #NEVER SET "only-grow-in-loaded-chunks" FALSE IF YOU DON'T DISABLE THE THREE FEATURES MENTIONED ABOVE.
  #Otherwise it would be laggy because too many data in cache.
  only-grow-in-loaded-chunks: true
  
  #Should all the worlds' crops grow?
  #This is useful for per player per world server.
  #In this mode, whitelist world can only have one as the standard of time & season judgment.
  all-world-grow: false

  #can player harvest crops with right click?
  #if set "false" crops can't be harvested repeatedly
  right-click-harvest: true

  #If "right-click-harvest" is true
  #Should player be allowed to harvest with items in hand
  harvest-with-empty-hand: true