#Don't change
config-version: '14'

# lang: english / spanish / chinese
lang: english

integration:
  # AntiGrief
  Residence: false
  WorldGuard: false
  Kingdoms: false
  GriefDefender: false
  PlotSquared: false
  Towny: false
  Lands: false
  GriefPrevention: false
  CrashClaim: false
  BentoBox: false
  # Skill Xp
  AureliumSkills: false
  mcMMO: false
  MMOCore: false
  EcoSkills: false
  JobsReborn: false
  # Season
  RealisticSeasons: false

worlds:
  # This is designed for servers that using a separate folder for worlds
  worlds-folder: ''
  # Mode: whitelist/blacklist
  # Requires a restart when changing this
  mode: whitelist
  list:
    - world

optimization:
  # Recommend enabling this to prevent large quantities of crops/itemframes lagging the server
  # When you are using both item_frame mode and ItemsAdder, you should set "max-furniture-vehicles-per-chunk" in ItemsAdder's config.yml to a higher value
  limitation:
    enable: true
    # max amount per chunk
    tripwire-amount: 64
    itemframe-amount: 64

  # Disable the water particles when using watering-cans
  disable-water-particles: false
  # Disable the animation when sprinkler works
  disable-sprinkler-animation: false
  # Auto back up the data when a world is unloaded
  auto-back-up: true

mechanics:
  # Mode: tripwire/item_frame
  crops-mode: tripwire

  # If enabled, crops would start growing at about 7am(at most 5 seconds inaccuracy) and finish growing in the rest of the day
  # Note: All the crops can only start growing when a world's time is about 7am, so when a world is loaded and its time is 8am,
  #       crops would not grow in this day. You can enable time compensation make the crops grow when starting the server.
  auto-grow:
    enable: true
    # For example, the time to start growing is 1000ticks(7am),
    # sprinklers would finish their work in a random time between 1000~1300ticks,
    # Pot would start drying in a random time between 1300~1500ticks
    # and crops would grow in a random time between 1500~21500ticks
    sprinkler-work-time: 300
    pot-dry-time: 200
    crops-grow-time: 20000
    # Crops would start growing instantly when the world is loaded instead of waiting for the second day's 7am
    time-compensation: true
  # If the pot is wet, crop would 100% grow a stage per day
  # Otherwise they would have a lower chance to grow.
  # Recommend setting it to a value higher than 0 to make sure every crop can be ripe even if
  # players don't take care of them, this is good for server performance because crop data would
  # be removed from data file when the crop is ripe to avoid affecting server performance in the long term
  dry-pot-grow-chance: 0.5
  # Can player harvest crops with right click?
  # if set "false" crops can't be harvested repeatedly
  right-click-harvest:
    enable: true
    require-empty-hand: true
  # Should player be prevented from planting if wrong season
  prevent-plant-if-wrong-season: true
  # Should player be notified of the wrong season?
  should-notify-if-wrong-season: true

  fill:
    watering-can-to-sprinkler: 1
    water-bucket-to-sprinkler: 3
    waterblock-to-watering-can: 1

  # Will bone meal accelerate the growth of crop
  bone-meal:
    enable: true
    chance: 0.5
    success-particle: VILLAGER_HAPPY
  # Season mechanic
  # Crops would go to death stage if growing in wrong seasons
  # Season would not affect ripe crops(for better performance and friendly player's experience)
  season:
    enable: true
    # If you want all the worlds to share the same season
    sync-seasons:
      enable: false
      world: world

    auto-season-change:
      # If enabled, setseason command would only work for only one day
      enable: true
      #duration of each season
      duration: 28
    greenhouse:
      enable: true
      #effective range
      range: 5
  # During the crop grow progress, crops have little chance to be eaten by a crow
  # Place a scarecrow would protect the crops in this chunk
  crow:
    enable: true
    chance: 0.005

  # 17/2/1 means 85%/10%/5%
  # 2/2/1 means 40%/40%/20%
  default-quality-ratio: 17/2/1

  # A crop would go to dead stage if the sky-light level is lower than a value.
  dead-if-no-sky-light:
    enable: true
    level: 10

  vanilla-crops:
    # Can vanilla crops be harvest with right clicks
    right-click-harvest: false
    # Totally prevent player from planting these vanilla crops in farmland
    prevent-plant:
      enable: false
      list:
        - WHEAT
        - CARROTS
        - POTATOES
        - BEETROOTS
    # Convert vanilla items into CustomCrops crops
    # You need to make extra CustomCrops/IA/Oraxen configs/models for these crops
    # This makes it possible to make vanilla crops have a better mechanic
    convert-to-customcrops:
      enable: false
      list:
        WHEAT_SEEDS: wheat
        CARROT: carrot
        POTATO: potato
        BEETROOT_SEEDS: beetroot


sounds:
  water-pot:
    enable: true
    sound: minecraft:block.water.ambient
    type: player
  add-water-to-can:
    enable: true
    sound: minecraft:item.bucket.fill
    type: player
  add-water-to-sprinkler:
    enable: true
    sound: minecraft:item.bucket.fill
    type: player
  place-sprinkler:
    enable: true
    sound: minecraft:block.bone_block.place
    type: player
  plant-seed:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  use-fertilizer:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  harvest-crops:
    enable: true
    sound: minecraft:block.crop.break
    type: player
  bonemeal:
    enable: true
    sound: minecraft:item.hoe.till
    type: player
  surveyor:
    enable: true
    sound: minecraft:block.note_block.pling
    type: player


# Hologram information
hologram:
  # Fertilizer infomation
  fertilizer-info:
    enable: true
    y-offset: 0.8
    duration: 1
    text: '<font:customcrops:default>{fertilizer} </font><white>{times}<gray>/<white>{max_times}'
  # Sprinkler infomation
  sprinkler-info:
    enable: true
    y-offset: 0.8
    duration: 1
    # available variables {water} {max_water}
    left: '<font:customcrops:default>뀂'
    full: '뀁뀃'
    empty: '뀁뀄'
    right: '뀁뀅</font>'



actionbar:
  # Should actionbar be sent when using watering-can
  enable: true
  # Available variables  {water} {max_water}
  left: '<font:customcrops:default>뀂'
  full: '뀁뀃'
  empty: '뀁뀄'
  right: '뀁뀅</font>'



season-broadcast:
  enable: true
  spring:
    - '<#3CB371>Spring is coming!'
  summer:
    - '<#FFFFE0>Summer is coming!'
  autumn:
    - '<#FF8C00>Autumn is coming!'
  winter:
    - '<#87CEFA>Winter is coming!'

season-change-command:
  enable: false
  spring:
    - 'say spring is coming!'


watering-can-lore:
  # Should watering-can has dynamic lore according to the water amount
  enable: true
  # Only packets can remain the former lore, otherwise the lore would be replaced
  packets:
    # Should watering-can's lore be sent by packets
    # Wouldn't work in creative mode for safety
    enable: true
    # true: top / false: bottom
    top-or-bottom: true
  # Lore format
  # Available variables: {water_bar}
  # {water}current water {max_water}max storage
  lore:
    - '<italic:false><white>{water_bar}'
    - '<italic:false><gray>Right click water to add water to the can.'
  water-bar:
    left: '<font:customcrops:default>뀂'
    full: '뀁뀃'
    empty: '뀁뀄'
    right: '뀁뀅</font>'
