name: CustomCrops
version: '1.2'
main: net.momirealms.customcrops.CustomCrops
api-version: 1.18
depend: [ ItemsAdder , ProtocolLib ]
softdepend: [ PlaceholderAPI , Kingdoms , Residence , WorldGuard ]
authors: [ XiaoMoMi ]
commands:
  customcrops:
    permission-message: No Permission