name: CustomCrops
version: '1.5.8'
main: net.momirealms.customcrops.CustomCrops
api-version: 1.16
depend:
  - ItemsAdder
  - ProtocolLib
softdepend:
  - PlaceholderAPI
  - Residence
  - Kingdoms
  - WorldGuard
  - GriefDefender
  - PlotSquared
  - Towny
  - Lands
authors: [ XiaoMoMi ]
commands:
  customcrops:
    usage: /customcrops <args>