name: CustomCrops
version: '1.2.7'
main: net.momirealms.customcrops.CustomCrops
api-version: 1.16
depend: [ ItemsAdder , ProtocolLib ]
softdepend: [ PlaceholderAPI ]
authors: [ XiaoMoMi ]
commands:
  customcrops:
    permission-message: No Permission