name: CustomCrops
version: '1.4.7'
main: net.momirealms.customcrops.CustomCrops
api-version: 1.16
depend:
  - ItemsAdder
softdepend:
  - PlaceholderAPI
  - Residence
  - Kingdoms
  - WorldGuard
  - GriefDefender
authors: [ XiaoMoMi ]
commands:
  customcrops:
    usage: /customcrops <args>
    permission-message: No Permission
    permission: customcrops.admin