name: CustomCrops
version: '${version}'
main: net.momirealms.customcrops.CustomCrops
api-version: 1.17
load: POSTWORLD
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
softdepend:
  - ItemsAdder
  - Oraxen
  - PlaceholderAPI
  - mcMMO
  - AureliumSkills
  - MMOCore
  - EcoSkills
  - RealisticSeasons
  - Jobs
  - IridiumSkyblock
  - SuperiorSkyBlock2
  - Residence
  - Kingdoms
  - WorldGuard
  - GriefDefender
  - PlotSquared
  - Towny
  - Lands
  - GriefPrevention
  - CrashClaim
  - BentoBox
  - EcoJobs
  - BattlePass
  - BetonQuest
  - ClueScrolls
  - HuskTowns
commands:
  customcrops:
    usage: /customcrops <args>
    permission: customcrops.admin
    aliases:
      - ccrops
permissions :
  customcrops.*:
    default: op
    children:
      customcrops.admin: true
      customcrops.reload: true
      customcrops.help: true
      customcrops.about: true
      customcrops.setdate: true
      customcrops.setseason: true
  customcrops.reload:
    default: op
  customcrops.help:
    default: op
  customcrops.about:
    default: op
  customcrops.setdate:
    default: op
  customcrops.setseason:
    default: op